# docker-compose.yml
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/ays
      - CACHE_TTL=${CACHE_TTL}
      - FALLBACK_LANGUAGE=${FALLBACK_LANGUAGE}
      - JWT_SECRET=${JWT_SECRET}
      - SEED_ADMIN_SECRET=${SEED_ADMIN_SECRET}
      - SEED_ALL_SECRET=${SEED_ALL_SECRET}
      - INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    depends_on:
      - mongodb
    networks:
      - ays-network

  mongodb:
    image: docker.io/library/mongo:6.0
    volumes:
      - ./mongo_data:/data/db
    networks:
      - ays-network

networks:
  ays-network:
    driver: bridge

# Deleted named volume for easier debugging

